### PR TITLE
Allow setting of the run name

### PR DESCRIPTION
**Pull request by rmhartog**
We are running tests from different branches within our CI environment. Because it's not currently possible to set the run name, it becomes hard to distinguish the runs. This PR allows the run name to be set, for example to the branch name or CI build number.

### CODE REVIEW

**Comment by hjanuschka** [comment]
@rmhartog many thx for your contribution, i think its a great change 🎉  , what run name will we used if the new param is unset?

**Comment by rmhartog** [comment]
Currently the name of the binary is used if it is unset, my runs were named 'application.apk' before.

**Comment by hjanuschka** [comment]
thx, i am just currently not able to test it quickly, nice to know that it fallsback to the behaviour before this PR.

many thx for your contribution!

**Comment by hjanuschka** [comment]
Released in v0.1.7 🎉

**Comment by rmhartog** [comment]
Thanks 🚀

**Pull request merged**
